# .rubocop.yml

# Use the default configuration as a base
#inherit_from:
#  - https://raw.githubusercontent.com/rubocop-hq/rubocop/master/config/default.yml

# Customize the configuration to your liking
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'Fastfile'
    - 'Pluginfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'Gemfile'
    - 'Gemfile.lock'

Style/Documentation:
  Enabled: true
  ParameterIndentWidth: 2
  ReturnIndent: true
  TreatCommentsAsGroupSeparators: true
  UseYARD: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
  Max: 20

Metrics/LineLength:
  Enabled: true
  Max: 120

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true
